baseURL = "/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "Glossover by Simpery"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Get Learning'
  homepage_intro = 'A website that keeps a track of everything we learned in spanish.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "This is  just a website for keeping track of everything we learned in spanish."
    meta_og_title = "Spanish Glossary"
    meta_og_type = "website"
    meta_og_url = "https://spanish.fuckht.ml"
    meta_og_image = ""
    meta_og_description = "This is  just a website for keeping track of everything we learned in spanish."
    meta_twitter_card = "summary"
    meta_twitter_site = "@NotSimpery"
    meta_twitter_creator = "@NotSimpery"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"

  [params.footer]
    copyright_text = 'Glossary built by <a class="zerostatic" href="https://www.fuckht.ml">Simpery</a>'
